export interface Manual {
  id: string;
  title: string;
  type: "매뉴얼" | "서류";
  url: string;
  homepage: string[];
  homepageMid?: string[];
  homepageSub?: string[];
  department: string[];
  employmentType: string[];
  role: string[];
}

export interface HpNode {
  label: string;
  children?: HpNode[];
}

export const HP_TREE: HpNode[] = [
  { label: "교육" },
  {
    label: "번역",
    children: [
      { label: "아랍어 번역" },
      { label: "영상번역" },
      { label: "웹툰번역" },
    ],
  },
  {
    label: "문서",
    children: [
      { label: "비즈문서" },
      { label: "법률문서" },
      { label: "의학문서" },
    ],
  },
  {
    label: "전시회",
    children: [
      { label: "박물관" },
      { label: "전시회" },
      { label: "관광지" },
    ],
  },
];

export const FILTER_OPTIONS = {
  homepage: ["교육", "번역", "문서", "전시회"],
  homepageMid: {
    번역: ["아랍어 번역", "영상번역", "웹툰번역"],
    문서: ["비즈문서", "법률문서", "의학문서"],
    전시회: ["박물관", "전시회", "관광지"],
  } as Record<string, string[]>,
  department: [
    "기업관리팀",
    "상담팀",
    "기획팀",
    "개발팀",
    "비서팀",
    "회계/총무팀",
    "디자인",
    "인사팀",
    "마케팅팀",
    "영업팀",
    "헤드헌팅팀",
    "강사팀",
    "커리큘럼·교재팀",
    "문제은행팀",
    "인증증명 서류",
    "원어민 강사",
    "학생 관리",
  ],
  employmentType: ["프리랜서", "파트타임", "정직원", "계약직"],
  role: [
    "외국인",
    "한국인",
    "알바",
    "신입",
    "강사",
    "팀장",
    "개발",
    "외부",
    "임원",
    "번역사",
    "분야별 전문가",
  ],
};

export const FILTER_LABELS: Record<string, string> = {
  homepage: "홈페이지 분류",
  department: "부서 분류",
  employmentType: "인물 1분류 (고용 형태)",
  role: "인물 2분류 (직군/특성)",
};

export const manuals: Manual[] = [
  {
    id: "1",
    title: "신입 사원 온보딩 가이드",
    type: "매뉴얼",
    url: "https://example.com/manuals/onboarding",
    homepage: ["교육"],
    department: ["인사팀"],
    employmentType: ["정직원"],
    role: ["신입", "한국인"],
  },
  {
    id: "2",
    title: "원어민 강사 수업 운영 매뉴얼",
    type: "매뉴얼",
    url: "https://example.com/manuals/native-teacher-class",
    homepage: ["교육"],
    department: ["원어민 강사", "강사팀"],
    employmentType: ["프리랜서", "정직원"],
    role: ["외국인", "강사"],
  },
  {
    id: "3",
    title: "번역 프로젝트 진행 절차서",
    type: "매뉴얼",
    url: "https://example.com/manuals/translation-process",
    homepage: ["번역"],
    homepageMid: ["영상번역"],
    department: ["기획팀"],
    employmentType: ["프리랜서", "정직원"],
    role: ["번역사", "한국인"],
  },
  {
    id: "4",
    title: "학생 관리 시스템(LMS) 사용 매뉴얼",
    type: "매뉴얼",
    url: "https://example.com/manuals/lms-guide",
    homepage: ["교육"],
    department: ["학생 관리", "개발팀"],
    employmentType: ["정직원"],
    role: ["한국인", "개발"],
  },
  {
    id: "5",
    title: "기업 고객 상담 응대 매뉴얼",
    type: "매뉴얼",
    url: "https://example.com/manuals/corporate-consulting",
    homepage: ["교육", "번역"],
    homepageMid: ["아랍어 번역"],
    department: ["기업관리팀", "상담팀", "영업팀"],
    employmentType: ["정직원"],
    role: ["한국인"],
  },
  {
    id: "6",
    title: "마케팅 캠페인 기획 가이드",
    type: "매뉴얼",
    url: "https://example.com/manuals/marketing-campaign",
    homepage: ["문서"],
    homepageMid: ["비즈문서"],
    department: ["마케팅팀", "기획팀"],
    employmentType: ["정직원"],
    role: ["한국인", "팀장"],
  },
  {
    id: "7",
    title: "프리랜서 계약 및 정산 안내서",
    type: "매뉴얼",
    url: "https://example.com/manuals/freelancer-contract",
    homepage: ["문서"],
    homepageMid: ["법률문서"],
    department: ["회계/총무팀", "인사팀"],
    employmentType: ["프리랜서"],
    role: ["외국인", "한국인", "번역사", "강사"],
  },
  {
    id: "8",
    title: "파트타임 근무자 출퇴근 관리 지침",
    type: "매뉴얼",
    url: "https://example.com/manuals/parttime-attendance",
    homepage: ["문서"],
    department: ["인사팀", "회계/총무팀"],
    employmentType: ["파트타임"],
    role: ["알바", "한국인"],
  },
  {
    id: "9",
    title: "개발팀 코드 리뷰 가이드라인",
    type: "매뉴얼",
    url: "https://example.com/manuals/code-review",
    homepage: ["문서"],
    department: ["개발팀"],
    employmentType: ["정직원"],
    role: ["개발", "한국인", "신입"],
  },
  {
    id: "10",
    title: "교재 개발 프로세스 매뉴얼",
    type: "매뉴얼",
    url: "https://example.com/manuals/textbook-dev",
    homepage: ["교육"],
    department: ["커리큘럼·교재팀", "기획팀"],
    employmentType: ["정직원"],
    role: ["한국인", "팀장"],
  },
  {
    id: "11",
    title: "문제은행 출제 기준 안내서",
    type: "매뉴얼",
    url: "https://example.com/manuals/question-bank",
    homepage: ["교육"],
    department: ["문제은행팀"],
    employmentType: ["정직원", "프리랜서"],
    role: ["한국인", "강사"],
  },
  {
    id: "12",
    title: "헤드헌팅 후보자 관리 매뉴얼",
    type: "매뉴얼",
    url: "https://example.com/manuals/headhunting",
    homepage: ["문서"],
    department: ["헤드헌팅팀", "인사팀"],
    employmentType: ["정직원"],
    role: ["한국인", "팀장"],
  },
  {
    id: "13",
    title: "비서팀 일정 관리 및 보고 절차",
    type: "매뉴얼",
    url: "https://example.com/manuals/secretary-schedule",
    homepage: ["문서"],
    department: ["비서팀"],
    employmentType: ["정직원"],
    role: ["한국인"],
  },
  {
    id: "14",
    title: "임원 보안 정책 안내서",
    type: "매뉴얼",
    url: "https://example.com/manuals/executive-security",
    homepage: ["문서"],
    homepageMid: ["비즈문서"],
    department: ["비서팀", "개발팀"],
    employmentType: ["정직원"],
    role: ["임원", "팀장"],
  },
  {
    id: "15",
    title: "외국인 강사 비자 및 체류 안내",
    type: "매뉴얼",
    url: "https://example.com/manuals/foreign-visa",
    homepage: ["문서"],
    department: ["인사팀", "원어민 강사"],
    employmentType: ["프리랜서", "정직원"],
    role: ["외국인", "강사"],
  },
  {
    id: "16",
    title: "영업팀 CRM 시스템 사용 가이드",
    type: "매뉴얼",
    url: "https://example.com/manuals/crm-guide",
    homepage: ["문서"],
    department: ["영업팀"],
    employmentType: ["정직원"],
    role: ["한국인", "신입"],
  },
  {
    id: "17",
    title: "번역 품질 검수(QA) 체크리스트",
    type: "매뉴얼",
    url: "https://example.com/manuals/translation-qa",
    homepage: ["번역"],
    homepageMid: ["웹툰번역"],
    department: ["기획팀"],
    employmentType: ["프리랜서", "정직원"],
    role: ["번역사", "외국인", "한국인"],
  },
  {
    id: "18",
    title: "학생 상담 및 진로 가이드 매뉴얼",
    type: "매뉴얼",
    url: "https://example.com/manuals/student-counseling",
    homepage: ["교육"],
    department: ["상담팀", "학생 관리"],
    employmentType: ["정직원", "파트타임"],
    role: ["한국인"],
  },
  {
    id: "19",
    title: "외부 협력사 커뮤니케이션 지침",
    type: "매뉴얼",
    url: "https://example.com/manuals/partner-communication",
    homepage: ["문서"],
    department: ["기획팀", "영업팀"],
    employmentType: ["정직원"],
    role: ["외부", "팀장"],
  },
  {
    id: "20",
    title: "알바생 업무 인수인계 가이드",
    type: "매뉴얼",
    url: "https://example.com/manuals/parttime-handover",
    homepage: ["교육", "문서"],
    department: ["학생 관리", "강사팀"],
    employmentType: ["파트타임"],
    role: ["알바", "한국인"],
  },
  {
    id: "21",
    title: "회계 총무팀 월말 정산 매뉴얼",
    type: "매뉴얼",
    url: "https://example.com/manuals/accounting-monthly",
    homepage: ["문서"],
    department: ["회계/총무팀"],
    employmentType: ["정직원"],
    role: ["한국인"],
  },
  {
    id: "22",
    title: "기업 교육 프로그램 제안서 작성 가이드",
    type: "매뉴얼",
    url: "https://example.com/manuals/corporate-education-proposal",
    homepage: ["교육", "문서"],
    department: ["기업관리팀", "영업팀", "기획팀"],
    employmentType: ["정직원"],
    role: ["한국인", "팀장"],
  },
  {
    id: "23",
    title: "개발팀 배포 및 운영 가이드",
    type: "매뉴얼",
    url: "https://example.com/manuals/dev-deployment",
    homepage: ["문서"],
    department: ["개발팀"],
    employmentType: ["정직원"],
    role: ["개발", "팀장"],
  },
  {
    id: "24",
    title: "번역사 온보딩 및 툴 사용 안내",
    type: "매뉴얼",
    url: "https://example.com/manuals/translator-onboarding",
    homepage: ["번역", "교육"],
    homepageMid: ["아랍어 번역", "영상번역"],
    department: ["기획팀", "인사팀"],
    employmentType: ["프리랜서"],
    role: ["번역사", "외국인", "한국인"],
  },
  {
    id: "25",
    title: "전사 정보보안 정책 매뉴얼",
    type: "매뉴얼",
    url: "https://example.com/manuals/security-policy",
    homepage: ["문서"],
    department: ["개발팀", "인사팀"],
    employmentType: ["정직원", "프리랜서", "파트타임"],
    role: ["한국인", "외국인", "임원", "팀장", "신입"],
  },
  {
    id: "26",
    title: "기업 계약서",
    type: "서류",
    url: "https://example.com/docs/corporate-contract",
    homepage: ["문서"],
    homepageMid: ["법률문서"],
    department: ["기업관리팀"],
    employmentType: ["정직원"],
    role: ["한국인", "팀장"],
  },
  {
    id: "27",
    title: "정산 관리 보고서",
    type: "서류",
    url: "https://example.com/docs/settlement-report",
    homepage: ["문서"],
    homepageMid: ["비즈문서"],
    department: ["기업관리팀"],
    employmentType: ["정직원"],
    role: ["한국인", "팀장"],
  },
  {
    id: "28",
    title: "상담 기록(일별, 주별, 월별) 보고서",
    type: "서류",
    url: "https://example.com/docs/counseling-report",
    homepage: ["문서"],
    department: ["상담팀"],
    employmentType: ["정직원", "파트타임"],
    role: ["한국인"],
  },
  {
    id: "29",
    title: "개인별 상담기록지",
    type: "서류",
    url: "https://example.com/docs/individual-counseling",
    homepage: ["문서"],
    department: ["상담팀"],
    employmentType: ["정직원", "파트타임"],
    role: ["한국인"],
  },
  {
    id: "67",
    title: "상담 기록 서류",
    type: "서류",
    url: "https://example.com/docs/counseling-record-full",
    homepage: ["문서"],
    department: ["상담팀"],
    employmentType: ["정직원", "파트타임"],
    role: ["한국인"],
  },
  {
    id: "30",
    title: "기획서",
    type: "서류",
    url: "https://example.com/docs/planning-document",
    homepage: ["문서"],
    department: ["기획팀"],
    employmentType: ["정직원"],
    role: ["한국인", "팀장"],
  },
  {
    id: "31",
    title: "개발계획서",
    type: "서류",
    url: "https://example.com/docs/dev-plan",
    homepage: ["문서"],
    department: ["개발팀"],
    employmentType: ["정직원"],
    role: ["개발", "팀장"],
  },
  {
    id: "32",
    title: "대표님 관리 매뉴얼",
    type: "서류",
    url: "https://example.com/docs/ceo-management",
    homepage: ["문서"],
    department: ["비서팀"],
    employmentType: ["정직원"],
    role: ["한국인"],
  },
  {
    id: "33",
    title: "직원들 관리 (교육 양식)",
    type: "서류",
    url: "https://example.com/docs/staff-training",
    homepage: ["교육", "문서"],
    department: ["비서팀"],
    employmentType: ["정직원"],
    role: ["한국인"],
  },
  {
    id: "34",
    title: "거래처 관리 양식",
    type: "서류",
    url: "https://example.com/docs/vendor-management",
    homepage: ["문서"],
    department: ["비서팀"],
    employmentType: ["정직원"],
    role: ["한국인", "외부"],
  },
  {
    id: "35",
    title: "재직증명서",
    type: "서류",
    url: "https://example.com/docs/employment-certificate",
    homepage: ["문서"],
    department: ["회계/총무팀"],
    employmentType: ["정직원", "계약직", "파트타임"],
    role: ["한국인", "외국인"],
  },
  {
    id: "36",
    title: "경력증명서",
    type: "서류",
    url: "https://example.com/docs/career-certificate",
    homepage: ["문서"],
    department: ["회계/총무팀"],
    employmentType: ["정직원", "계약직"],
    role: ["한국인", "외국인"],
  },
  {
    id: "37",
    title: "업무확인서",
    type: "서류",
    url: "https://example.com/docs/work-confirmation",
    homepage: ["문서"],
    department: ["회계/총무팀"],
    employmentType: ["정직원", "계약직", "프리랜서"],
    role: ["한국인", "외국인"],
  },
  {
    id: "38",
    title: "근무확인서",
    type: "서류",
    url: "https://example.com/docs/attendance-confirmation",
    homepage: ["문서"],
    department: ["회계/총무팀"],
    employmentType: ["정직원", "계약직", "파트타임"],
    role: ["한국인", "외국인"],
  },
  {
    id: "39",
    title: "사직서",
    type: "서류",
    url: "https://example.com/docs/resignation-letter",
    homepage: ["문서"],
    department: ["회계/총무팀"],
    employmentType: ["정직원", "계약직"],
    role: ["한국인", "외국인"],
  },
  {
    id: "40",
    title: "급여명세서",
    type: "서류",
    url: "https://example.com/docs/salary-statement",
    homepage: ["문서"],
    department: ["회계/총무팀"],
    employmentType: ["정직원", "계약직", "파트타임", "프리랜서"],
    role: ["한국인", "외국인"],
  },
  {
    id: "41",
    title: "추천서, 봉사 확인서",
    type: "서류",
    url: "https://example.com/docs/recommendation-volunteer",
    homepage: ["문서"],
    department: ["회계/총무팀"],
    employmentType: ["정직원", "계약직", "파트타임"],
    role: ["한국인", "외국인"],
  },
  {
    id: "42",
    title: "회사 규정 로고, 이름, 기본틀",
    type: "서류",
    url: "https://example.com/docs/design-branding",
    homepage: ["문서"],
    department: ["디자인"],
    employmentType: ["정직원"],
    role: ["한국인"],
  },
  {
    id: "43",
    title: "온라인 디자인계획결과안",
    type: "서류",
    url: "https://example.com/docs/design-online-plan",
    homepage: ["문서"],
    department: ["디자인"],
    employmentType: ["정직원"],
    role: ["한국인"],
  },
  {
    id: "44",
    title: "오프라인 디자인계획결과안",
    type: "서류",
    url: "https://example.com/docs/design-offline-plan",
    homepage: ["문서"],
    department: ["디자인"],
    employmentType: ["정직원"],
    role: ["한국인"],
  },
  {
    id: "45",
    title: "파트타임 직원 계약서",
    type: "서류",
    url: "https://example.com/docs/parttime-contract",
    homepage: ["문서"],
    department: ["인사팀"],
    employmentType: ["파트타임"],
    role: ["한국인", "외국인"],
  },
  {
    id: "46",
    title: "정직원 계약서",
    type: "서류",
    url: "https://example.com/docs/fulltime-contract",
    homepage: ["문서"],
    department: ["인사팀"],
    employmentType: ["정직원"],
    role: ["한국인", "외국인"],
  },
  {
    id: "47",
    title: "계약직 계약서",
    type: "서류",
    url: "https://example.com/docs/contract-worker",
    homepage: ["문서"],
    department: ["인사팀"],
    employmentType: ["계약직"],
    role: ["한국인", "외국인"],
  },
  {
    id: "48",
    title: "프리랜서 계약서",
    type: "서류",
    url: "https://example.com/docs/freelancer-contract-hr",
    homepage: ["문서"],
    department: ["인사팀"],
    employmentType: ["프리랜서"],
    role: ["한국인", "외국인"],
  },
  {
    id: "49",
    title: "분야별 전문가 계약서",
    type: "서류",
    url: "https://example.com/docs/expert-contract",
    homepage: ["문서"],
    department: ["인사팀"],
    employmentType: ["프리랜서", "계약직"],
    role: ["분야별 전문가", "한국인", "외국인"],
  },
  {
    id: "50",
    title: "번역사 계약서",
    type: "서류",
    url: "https://example.com/docs/translator-contract",
    homepage: ["문서", "번역"],
    homepageMid: ["법률문서"],
    department: ["인사팀"],
    employmentType: ["프리랜서", "계약직"],
    role: ["번역사", "한국인", "외국인"],
  },
  {
    id: "51",
    title: "한국강사 계약서",
    type: "서류",
    url: "https://example.com/docs/korean-teacher-contract",
    homepage: ["문서", "교육"],
    department: ["인사팀"],
    employmentType: ["프리랜서", "계약직", "정직원"],
    role: ["강사", "한국인"],
  },
  {
    id: "52",
    title: "외국인강사 계약서",
    type: "서류",
    url: "https://example.com/docs/foreign-teacher-contract",
    homepage: ["문서", "교육"],
    department: ["인사팀"],
    employmentType: ["프리랜서", "계약직", "정직원"],
    role: ["강사", "외국인"],
  },
  {
    id: "53",
    title: "마케팅안 계획안",
    type: "서류",
    url: "https://example.com/docs/marketing-plan",
    homepage: ["문서"],
    department: ["마케팅팀"],
    employmentType: ["정직원"],
    role: ["한국인", "팀장"],
  },
  {
    id: "54",
    title: "마케팅 결과 보고서",
    type: "서류",
    url: "https://example.com/docs/marketing-result-report",
    homepage: ["문서"],
    department: ["마케팅팀"],
    employmentType: ["정직원"],
    role: ["한국인", "팀장"],
  },
  {
    id: "55",
    title: "영업 계획안",
    type: "서류",
    url: "https://example.com/docs/sales-plan",
    homepage: ["문서"],
    department: ["영업팀"],
    employmentType: ["정직원"],
    role: ["한국인", "팀장"],
  },
  {
    id: "56",
    title: "영업 결과보고서",
    type: "서류",
    url: "https://example.com/docs/sales-result-report",
    homepage: ["문서"],
    department: ["영업팀"],
    employmentType: ["정직원"],
    role: ["한국인", "팀장"],
  },
  {
    id: "57",
    title: "고객 관리보고서와 통계결과보고서",
    type: "서류",
    url: "https://example.com/docs/customer-statistics-report",
    homepage: ["문서"],
    department: ["영업팀"],
    employmentType: ["정직원"],
    role: ["한국인", "팀장"],
  },
  {
    id: "58",
    title: "거래처 계약서",
    type: "서류",
    url: "https://example.com/docs/vendor-contract",
    homepage: ["문서"],
    department: ["영업팀"],
    employmentType: ["정직원"],
    role: ["한국인", "팀장", "외부"],
  },
  {
    id: "59",
    title: "매칭 계획",
    type: "서류",
    url: "https://example.com/docs/matching-plan",
    homepage: ["문서"],
    department: ["헤드헌팅팀"],
    employmentType: ["정직원"],
    role: ["한국인", "팀장"],
  },
  {
    id: "60",
    title: "강사구인계획과 홍보안",
    type: "서류",
    url: "https://example.com/docs/teacher-recruitment",
    homepage: ["교육", "문서"],
    department: ["강사팀"],
    employmentType: ["정직원"],
    role: ["한국인", "팀장", "강사"],
  },
  {
    id: "61",
    title: "강사 교육안과 관리안",
    type: "서류",
    url: "https://example.com/docs/teacher-training-plan",
    homepage: ["교육", "문서"],
    department: ["강사팀"],
    employmentType: ["정직원"],
    role: ["한국인", "팀장", "강사"],
  },
  {
    id: "62",
    title: "커리큘럼계획틀과 진행계획안",
    type: "서류",
    url: "https://example.com/docs/curriculum-plan",
    homepage: ["교육", "문서"],
    department: ["커리큘럼·교재팀"],
    employmentType: ["정직원"],
    role: ["한국인", "팀장"],
  },
  {
    id: "63",
    title: "문제은행계획틀과 진행계획안",
    type: "서류",
    url: "https://example.com/docs/question-bank-plan",
    homepage: ["교육", "문서"],
    department: ["문제은행팀"],
    employmentType: ["정직원"],
    role: ["한국인", "팀장"],
  },
  {
    id: "64",
    title: "번역 인증 확인서",
    type: "서류",
    url: "https://example.com/docs/translation-certification",
    homepage: ["번역", "문서"],
    homepageMid: ["아랍어 번역", "영상번역", "웹툰번역"],
    department: ["인증증명 서류"],
    employmentType: ["프리랜서", "정직원", "계약직"],
    role: ["번역사", "한국인", "외국인"],
  },
  {
    id: "65",
    title: "전문분야 인증 확인서",
    type: "서류",
    url: "https://example.com/docs/field-certification",
    homepage: ["문서"],
    department: ["인증증명 서류"],
    employmentType: ["프리랜서", "정직원", "계약직"],
    role: ["분야별 전문가", "한국인", "외국인"],
  },
  {
    id: "66",
    title: "전문가 인증확인서",
    type: "서류",
    url: "https://example.com/docs/expert-certification",
    homepage: ["문서"],
    department: ["인증증명 서류"],
    employmentType: ["프리랜서", "정직원", "계약직"],
    role: ["분야별 전문가", "한국인", "외국인"],
  },
];
