import type { Applicant } from "./types";

export const MOCK_APPLICANTS: Applicant[] = [
  {
    applicant_id: "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
    status: "pending",
    applied_at: "2026-02-10 14:30",
    basic: {
      name: "김번역",
      email: "kim@translator.kr",
      phone: "010-1234-5678",
      birthDate: "1990-01-01",
      course: "AI 번역",
      job: "전문번역사",
      introduction:
        "영한/한영 전문 번역 10년 경력. 법률, IT, 의학 분야 전문 번역을 주로 수행해왔으며, 다수의 출판 번역 프로젝트에 참여하였습니다.",
    },
    application: {
      available_languages: ["영어", "한국어"],
      available_time: "종일",
      experience: "5년 이상",
      occupation: ["전문번역사"],
      education: "석사",
      call_time: "언제나 가능",
    },
    extra: {
      work_goals: ["전문번역 프리랜서"],
      language_certs: ["영어"],
      overseas_experience: "있음",
      mt_experience: "있음",
    },
  },
  {
    applicant_id: "b2c3d4e5-f6a7-8901-bcde-f12345678901",
    status: "pending",
    applied_at: "2026-02-09 10:15",
    basic: {
      name: "이일본",
      email: "lee@japan-trans.com",
      phone: "010-9876-5432",
      birthDate: "1992-05-15",
      course: "ITT 번역교육",
      job: "직장인",
      introduction:
        "일본 도쿄 유학 4년, 일본어능력시험 N1 취득. 만화, 라이트노벨, 게임 로컬라이징 번역 경험이 풍부합니다.",
    },
    application: {
      available_languages: ["일본어", "한국어", "영어"],
      available_time: "오후 (12:00~18:00)",
      experience: "3년~5년",
      occupation: ["번역프리랜서"],
      education: "학사",
      call_time: "오후 (12:00~18:00)",
    },
    extra: {
      work_goals: ["전문번역 프리랜서", "추가 부수입"],
      language_certs: ["일본어", "영어"],
      overseas_experience: "있음",
      mt_experience: "있음",
    },
  },
  {
    applicant_id: "c3d4e5f6-a7b8-9012-cdef-123456789012",
    status: "approved",
    applied_at: "2026-02-05 16:45",
    basic: {
      name: "박중국",
      email: "park@china-lang.com",
      phone: "010-5555-3333",
      birthDate: "1988-11-20",
      course: "프롬프트",
      job: "기타",
      introduction:
        "중국어 통번역 석사 졸업. 비즈니스 중국어 및 기술 문서 번역 전문입니다.",
    },
    application: {
      available_languages: ["중국어", "한국어"],
      available_time: "종일",
      experience: "3년~5년",
      occupation: ["전문번역사", "직장인"],
      education: "석사",
      call_time: "오전 (09:00~12:00)",
    },
    extra: {
      work_goals: ["전문번역 프리랜서"],
      language_certs: ["중국어"],
      overseas_experience: "있음",
      mt_experience: "없음",
    },
  },
  {
    applicant_id: "d4e5f6a7-b8c9-0123-defa-234567890123",
    status: "rejected",
    applied_at: "2026-02-03 09:20",
    rejection_reason: "자기소개란 미기입 - 재신청 요청",
    basic: {
      name: "최학생",
      email: "choi@student.ac.kr",
      phone: "010-7777-8888",
      birthDate: "2002-03-10",
      course: "TESOL",
      job: "학생",
      introduction: "",
    },
    application: {
      available_languages: ["영어"],
      available_time: "저녁 (18:00~22:00)",
      experience: "신입 (경험 없음)",
      occupation: ["학생"],
      education: "학사",
      call_time: "저녁 (18:00~22:00)",
    },
    extra: {
      work_goals: ["영어공부", "추가 부수입"],
      language_certs: ["영어"],
      overseas_experience: "없음",
      mt_experience: "전혀 모름",
    },
  },
  {
    applicant_id: "e5f6a7b8-c9d0-1234-efab-345678901234",
    status: "pending",
    applied_at: "2026-02-11 11:50",
    basic: {
      name: "정프리",
      email: "jung@freelance.kr",
      phone: "010-2222-4444",
      birthDate: "1995-08-25",
      course: "AI윤리",
      job: "기타",
      introduction:
        "다국어 번역 프리랜서 3년차. 영어, 일본어, 중국어 3개 국어 번역 가능합니다. 기계번역 후처리(MTPE) 경험도 다수 보유하고 있습니다.",
    },
    application: {
      available_languages: ["영어", "일본어", "중국어", "한국어"],
      available_time: "종일",
      experience: "3년~5년",
      occupation: ["번역프리랜서"],
      education: "학사",
      call_time: "언제나 가능",
    },
    extra: {
      work_goals: ["전문번역 프리랜서", "추가 부수입"],
      language_certs: ["영어", "일본어", "중국어"],
      overseas_experience: "있음",
      mt_experience: "있음",
    },
  },
];
